import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import apiKeysRouter from "./apikeys";
import contactsRouter from "./contacts";
import groupsRouter from "./groups";
import tagsRouter from "./tags";
import templatesRouter from "./templates";
import webhookRouter from "./webhook";
import conversationsRouter from "./conversations";
import campaignsRouter from "./campaigns";
import billingRouter from "./billing";
import phoneNumbersRouter from "./phonenumbers";
import whatsappProfileRouter from "./whatsapp-profile";
import metaComplianceRouter from "./meta-compliance";
import integrationRouter from "./integration";
import mediaRouter from "./media";
import agentsRouter from "./agents";
import cannedMessagesRouter from "./canned-messages";
import livechatSettingsRouter from "./livechat-settings";
import attributesRouter from "./attributes";
import flowsRouter from "./flows";
import chatbotRouter from "./chatbot";
import servicePricingRouter from "./service-pricing";
import adminRouter from "./admin";
import audienceSegmentsRouter from "./audience-segments";
import masterAdminRouter from "./master-admin";
import notificationsRouter from "./notifications";
import clientWebhooksRouter from "./client-webhooks";
import metaInsightsRouter from "./meta-insights";

const router: IRouter = Router();

// These routers MUST come first — they have no auth and must not be intercepted.
router.use(webhookRouter);
router.use(metaComplianceRouter);

router.use(healthRouter);
router.use(authRouter);
router.use(masterAdminRouter);
router.use(notificationsRouter);
router.use(clientWebhooksRouter);
router.use(metaInsightsRouter);
router.use(apiKeysRouter);
router.use(contactsRouter);
router.use(groupsRouter);
router.use(tagsRouter);
router.use(templatesRouter);
router.use(conversationsRouter);
router.use(campaignsRouter);
router.use(billingRouter);
router.use(phoneNumbersRouter);
router.use(whatsappProfileRouter);
router.use(integrationRouter);
router.use(mediaRouter);
router.use(agentsRouter);
router.use(cannedMessagesRouter);
router.use(livechatSettingsRouter);
router.use(attributesRouter);
router.use(flowsRouter);
router.use(chatbotRouter);
router.use(servicePricingRouter);
router.use(adminRouter);
router.use(audienceSegmentsRouter);

export default router;
