export interface NodeDef {
  type: string;
  label: string;
  color: string;
  bg: string;
  textColor: string;
  icon: string;
  category: 'trigger' | 'message' | 'action' | 'logic' | 'advanced';
  description: string;
  defaultData: Record<string, unknown>;
  maxInputs?: number;
  maxOutputs?: number;
  outputHandles?: Array<{ id: string; label: string; color: string }>;
}

export const NODE_DEFS: NodeDef[] = [
  {
    type: 'start',
    label: 'Start',
    color: '#1e3a8a',
    bg: '#dbeafe',
    textColor: '#1e3a8a',
    icon: 'Play',
    category: 'trigger',
    description: 'Entry point of the flow',
    maxInputs: 0,
    defaultData: { label: 'Start', description: '' },
  },
  {
    type: 'keyword',
    label: 'Keyword',
    color: '#6d28d9',
    bg: '#ede9fe',
    textColor: '#5b21b6',
    icon: 'Hash',
    category: 'trigger',
    description: 'Trigger on matching keyword',
    defaultData: { keywords: [], matchType: 'contains', caseSensitive: false },
  },
  {
    type: 'textReply',
    label: 'Text Reply',
    color: '#059669',
    bg: '#d1fae5',
    textColor: '#065f46',
    icon: 'MessageSquare',
    category: 'message',
    description: 'Send a text message',
    defaultData: { message: '', typingDelay: 1 },
  },
  {
    type: 'mediaReply',
    label: 'Media Reply',
    color: '#d97706',
    bg: '#fef3c7',
    textColor: '#92400e',
    icon: 'Image',
    category: 'message',
    description: 'Send an image, video or document',
    defaultData: { mediaType: 'image', mediaUrl: '', caption: '' },
  },
  {
    type: 'listReply',
    label: 'List Reply',
    color: '#0891b2',
    bg: '#cffafe',
    textColor: '#0e7490',
    icon: 'List',
    category: 'message',
    description: 'Send an interactive list',
    defaultData: {
      header: '',
      body: '',
      footer: '',
      buttonText: 'Choose',
      sections: [{ title: 'Options', rows: [{ id: '1', title: 'Option 1', description: '' }] }],
    },
  },
  {
    type: 'ctaButton',
    label: 'CTA Button',
    color: '#db2777',
    bg: '#fce7f3',
    textColor: '#9d174d',
    icon: 'MousePointerClick',
    category: 'message',
    description: 'Interactive reply buttons (max 3)',
    defaultData: { body: '', footer: '', buttons: [{ id: '1', title: 'Button 1' }] },
  },
  {
    type: 'template',
    label: 'Template',
    color: '#4f46e5',
    bg: '#e0e7ff',
    textColor: '#3730a3',
    icon: 'Layout',
    category: 'message',
    description: 'Send a Meta-approved template',
    defaultData: { templateName: '', language: 'en_US', headerVar: '', variables: [], ctaUrl: '', ctaLabel: '' },
  },
  {
    type: 'location',
    label: 'Location',
    color: '#16a34a',
    bg: '#dcfce7',
    textColor: '#166534',
    icon: 'MapPin',
    category: 'message',
    description: 'Request or send location',
    defaultData: { action: 'request', message: 'Please share your location', lat: '', lng: '', locationName: '' },
  },
  {
    type: 'catalog',
    label: 'Catalog',
    color: '#b45309',
    bg: '#fef9c3',
    textColor: '#713f12',
    icon: 'ShoppingBag',
    category: 'message',
    description: 'Share product catalog',
    defaultData: { bodyText: 'Check out our products!', footerText: '', productIds: [], catalogId: '' },
  },
  {
    type: 'flowReply',
    label: 'Flow Reply',
    color: '#7c3aed',
    bg: '#f3e8ff',
    textColor: '#6b21a8',
    icon: 'Workflow',
    category: 'message',
    description: 'Trigger a WhatsApp Flow form',
    defaultData: { flowId: '', headerText: '', bodyText: 'Please complete the form.', ctaLabel: 'Open Form', mode: 'draft' },
  },
  {
    type: 'tag',
    label: 'Tag',
    color: '#ca8a04',
    bg: '#fefce8',
    textColor: '#854d0e',
    icon: 'Tag',
    category: 'action',
    description: 'Add or remove contact tags',
    defaultData: { action: 'add', tags: [] },
  },
  {
    type: 'assignAgent',
    label: 'Assign Agent',
    color: '#2563eb',
    bg: '#dbeafe',
    textColor: '#1d4ed8',
    icon: 'UserCheck',
    category: 'action',
    description: 'Assign conversation to an agent',
    defaultData: { assignType: 'specific', agentId: '', teamId: '', priority: 'normal', note: '' },
  },
  {
    type: 'attribute',
    label: 'Set Attribute',
    color: '#7c3aed',
    bg: '#ede9fe',
    textColor: '#4c1d95',
    icon: 'Database',
    category: 'action',
    description: 'Set contact attributes',
    defaultData: { attributes: [{ name: '', operator: 'set', value: '' }] },
  },
  {
    type: 'condition',
    label: 'Condition',
    color: '#ea580c',
    bg: '#ffedd5',
    textColor: '#c2410c',
    icon: 'GitBranch',
    category: 'logic',
    description: 'Branch based on conditions',
    outputHandles: [
      { id: 'true', label: 'True', color: '#16a34a' },
      { id: 'false', label: 'False', color: '#dc2626' },
    ],
    defaultData: { conditions: [{ field: 'contact.name', operator: 'equals', value: '' }], logicType: 'AND' },
  },
  {
    type: 'customApi',
    label: 'Custom API',
    color: '#dc2626',
    bg: '#fee2e2',
    textColor: '#b91c1c',
    icon: 'Code',
    category: 'advanced',
    description: 'Make HTTP API requests',
    defaultData: { method: 'GET', url: '', headers: [], body: '', responseMapping: [], testResult: null },
  },
  {
    type: 'integration',
    label: 'Integration',
    color: '#0369a1',
    bg: '#e0f2fe',
    textColor: '#0c4a6e',
    icon: 'Link',
    category: 'advanced',
    description: 'Connect to external services',
    defaultData: { service: '', action: '', mappings: [] },
  },
  {
    type: 'errorHandler',
    label: 'Error Handler',
    color: '#9f1239',
    bg: '#ffe4e6',
    textColor: '#9f1239',
    icon: 'AlertTriangle',
    category: 'advanced',
    description: 'Handle flow errors gracefully',
    outputHandles: [
      { id: 'retry', label: 'Retry', color: '#d97706' },
      { id: 'fallback', label: 'Fallback', color: '#6b7280' },
    ],
    defaultData: { errorMessage: "Sorry, something went wrong. Please try again.", retryCount: 2, retryDelay: 3, fallbackFlowId: '' },
  },
];

export const NODE_DEF_MAP = Object.fromEntries(NODE_DEFS.map(d => [d.type, d]));

export const CATEGORIES = [
  { key: 'trigger', label: 'Triggers', emoji: '⚡' },
  { key: 'message', label: 'Messages', emoji: '💬' },
  { key: 'action', label: 'Actions', emoji: '⚙️' },
  { key: 'logic', label: 'Logic', emoji: '🔀' },
  { key: 'advanced', label: 'Advanced', emoji: '🔧' },
] as const;
