export interface NodeDef {
  type: string;
  label: string;
  color: string;       // header + handle color
  bg: string;          // light bg for header
  textColor: string;
  icon: string;        // lucide icon name
  category: 'trigger' | 'message' | 'action' | 'logic' | 'advanced';
  description: string;
  defaultData: Record<string, unknown>;
}

export const NODE_DEFS: NodeDef[] = [
  {
    type: 'start',
    label: 'Start',
    color: '#1e3a8a',
    bg: '#dbeafe',
    textColor: '#1e3a8a',
    icon: 'Play',
    category: 'trigger',
    description: 'Entry point of the flow',
    defaultData: { label: 'Start', description: '' },
  },
  {
    type: 'keyword',
    label: 'Keyword',
    color: '#6d28d9',
    bg: '#ede9fe',
    textColor: '#5b21b6',
    icon: 'Hash',
    category: 'trigger',
    description: 'Trigger on matching keyword',
    defaultData: { keywords: [], matchType: 'contains', caseSensitive: false },
  },
  {
    type: 'textReply',
    label: 'Text Reply',
    color: '#065f46',
    bg: '#d1fae5',
    textColor: '#065f46',
    icon: 'MessageSquare',
    category: 'message',
    description: 'Send a text message',
    defaultData: { message: '', typingDelay: 1 },
  },
  {
    type: 'mediaReply',
    label: 'Media Reply',
    color: '#92400e',
    bg: '#fef3c7',
    textColor: '#92400e',
    icon: 'Image',
    category: 'message',
    description: 'Send an image, video or document',
    defaultData: { mediaType: 'image', mediaUrl: '', caption: '' },
  },
  {
    type: 'listReply',
    label: 'List Reply',
    color: '#0e7490',
    bg: '#cffafe',
    textColor: '#0e7490',
    icon: 'List',
    category: 'message',
    description: 'Send an interactive list',
    defaultData: { header: '', body: '', footer: '', buttonText: 'Choose', sections: [{ title: 'Options', rows: [{ id: '1', title: 'Option 1', description: '' }] }] },
  },
  {
    type: 'ctaButton',
    label: 'CTA Button',
    color: '#9d174d',
    bg: '#fce7f3',
    textColor: '#9d174d',
    icon: 'MousePointerClick',
    category: 'message',
    description: 'Interactive reply buttons',
    defaultData: { body: '', footer: '', buttons: [{ id: '1', title: 'Button 1' }] },
  },
  {
    type: 'template',
    label: 'Template',
    color: '#3730a3',
    bg: '#e0e7ff',
    textColor: '#3730a3',
    icon: 'Layout',
    category: 'message',
    description: 'Send a Meta-approved template',
    defaultData: { templateName: '', language: 'en_US', variables: [] },
  },
  {
    type: 'tag',
    label: 'Tag',
    color: '#92400e',
    bg: '#fef9c3',
    textColor: '#854d0e',
    icon: 'Tag',
    category: 'action',
    description: 'Add or remove contact tags',
    defaultData: { action: 'add', tags: [] },
  },
  {
    type: 'condition',
    label: 'Condition',
    color: '#c2410c',
    bg: '#ffedd5',
    textColor: '#c2410c',
    icon: 'GitBranch',
    category: 'logic',
    description: 'Branch based on conditions',
    defaultData: { conditions: [{ field: '', operator: 'equals', value: '' }], logicType: 'AND' },
  },
  {
    type: 'assignAgent',
    label: 'Assign Agent',
    color: '#1d4ed8',
    bg: '#dbeafe',
    textColor: '#1d4ed8',
    icon: 'UserCheck',
    category: 'action',
    description: 'Assign conversation to an agent',
    defaultData: { assignType: 'specific', agentId: '', teamId: '' },
  },
  {
    type: 'customApi',
    label: 'Custom API',
    color: '#b91c1c',
    bg: '#fee2e2',
    textColor: '#b91c1c',
    icon: 'Code',
    category: 'advanced',
    description: 'Make HTTP API requests',
    defaultData: { method: 'GET', url: '', headers: [], body: '', responseMapping: [] },
  },
  {
    type: 'attribute',
    label: 'Attribute',
    color: '#4c1d95',
    bg: '#ede9fe',
    textColor: '#4c1d95',
    icon: 'Database',
    category: 'action',
    description: 'Set contact attributes',
    defaultData: { attributes: [{ name: '', value: '' }] },
  },
  {
    type: 'location',
    label: 'Location',
    color: '#166534',
    bg: '#dcfce7',
    textColor: '#166534',
    icon: 'MapPin',
    category: 'message',
    description: 'Request or send location',
    defaultData: { action: 'request', message: 'Please share your location', lat: '', lng: '', locationName: '' },
  },
  {
    type: 'integration',
    label: 'Integration',
    color: '#0c4a6e',
    bg: '#e0f2fe',
    textColor: '#0c4a6e',
    icon: 'Link',
    category: 'advanced',
    description: 'Connect to external services',
    defaultData: { service: '', action: '', mappings: [] },
  },
  {
    type: 'flowReply',
    label: 'Flow Reply',
    color: '#6b21a8',
    bg: '#f3e8ff',
    textColor: '#6b21a8',
    icon: 'Workflow',
    category: 'advanced',
    description: 'Trigger a WhatsApp Flow form',
    defaultData: { flowId: '', headerText: '', bodyText: 'Please complete the form.', ctaLabel: 'Open Form' },
  },
  {
    type: 'catalog',
    label: 'Catalog',
    color: '#713f12',
    bg: '#fef3c7',
    textColor: '#713f12',
    icon: 'ShoppingBag',
    category: 'message',
    description: 'Share product catalog',
    defaultData: { bodyText: '', footerText: '', productIds: [] },
  },
];

export const NODE_DEF_MAP = Object.fromEntries(NODE_DEFS.map(d => [d.type, d]));

export const CATEGORIES = [
  { key: 'trigger', label: 'Triggers' },
  { key: 'message', label: 'Messages' },
  { key: 'action', label: 'Actions' },
  { key: 'logic', label: 'Logic' },
  { key: 'advanced', label: 'Advanced' },
] as const;
